---
zabbix_template_mysql_name: "MySQL by tk"
zabbix_template_mysql_group: "Templates/Databases"

mysql_master_item_key: "mysql.get_status_variables[Default]"
mysql_master_item_interval: "60s"

mysql_dependent_items:
  - name: "MySQL Threads connected"
    key: "mysql.threads_connected"
    field: "Threads_connected"
  - name: "MySQL Threads running"
    key: "mysql.threads_running"
    field: "Threads_running"
  - name: "MySQL Max used connections"
    key: "mysql.max_used_connections"
    field: "Max_used_connections"
  - name: "MySQL Questions"
    key: "mysql.questions"
    field: "Questions"
  - name: "MySQL Select"
    key: "mysql.com_select"
    field: "Com_select"
  - name: "MySQL Insert"
    key: "mysql.com_insert"
    field: "Com_insert"
  - name: "MySQL Update"
    key: "mysql.com_update"
    field: "Com_update"
  - name: "MySQL Delete"
    key: "mysql.com_delete"
    field: "Com_delete"
  - name: "MySQL Aborted connects"
    key: "mysql.aborted_connects"
    field: "Aborted_connects"
