---
# Discovery Rule の作成と設定
- name: Create Discovery Rule under the Template
  community.zabbix.zabbix_discoveryrule:
    name: "df"
    template_name: "{{ zabbix_template_name }}"
    params:
        type: zabbix_agent
        key: 'vfs.fs.discovery'
        interval: 1h
        enabled: True
  register: discoveryrule_result

- name: Get current discovery rule filter
  uri:
    url: "{{ lookup('env', 'ZABBIX_URL') }}"
    method: POST
    headers:
      Content-Type: application/json-rpc
      Authorization: "Bearer {{ lookup('env', 'ZABBIX_API_TOKEN') }}"
    body_format: json
    body:
      jsonrpc: "2.0"
      method: discoveryrule.get
      params:
        itemids: "{{ discoveryrule_result.result[0].itemids[0] }}"
        selectFilter: extend
      id: 1
    return_content: yes
  register: current_filter
  check_mode: no

- name: Update discovery rule filter
  uri:
    url: "{{ lookup('env', 'ZABBIX_URL') }}"
    method: POST
    headers:
      Content-Type: application/json-rpc
      Authorization: "Bearer {{ lookup('env', 'ZABBIX_API_TOKEN') }}"
    body_format: json
    body:
      jsonrpc: "2.0"
      method: "discoveryrule.update"
      params:
        itemid: "{{ discoveryrule_result.result[0].itemids[0] }}"
        filter:
          evaltype: 0
          conditions:
            - macro: "{{ '{#FSNAME}' }}"
              value: "^/$|^/var/lib/mysql$|^/var/sy$|^/backup$"
              operator: 8
      id: 2
    return_content: yes
  register: discoveryrule_filter_result
  check_mode: no
    #changed_when: >
    #current_filter.json.result[0].filter.evaltype | string != "0" or
    #current_filter.json.result[0].filter.conditions | length == 0 or
    #current_filter.json.result[0].filter.conditions[0].macro != '{#FSNAME}' or
    #current_filter.json.result[0].filter.conditions[0].value != "^/$|^/var/lib/mysql$|^/var/sy$|^/backup$" or
    #current_filter.json.result[0].filter.conditions[0].operator | string != "8"
