---
# Template Items の作成
- name: Create template items
  community.zabbix.zabbix_item:
    name: "{{ item.name }}"
    template_name: "{{ zabbix_template_name }}"
    state: present
    params:
      type: "{{ 'calculated' if item.type | default('') == 'calculated' else 'zabbix_agent' }}"
      key: "{{ item.key }}"
      value_type: "{{ item.value_type }}"
      units: "{{ item.units | default(omit) }}"
      interval: "{{ item.interval }}"
      params: "{{ item.params | default(omit) }}"
  loop: "{{ zabbix_items }}"
  register: items_result
  changed_when: items_result.changed
