- name: Create template
  community.zabbix.zabbix_template:
    template_name: "{{ zabbix_template_name }}"
    template_groups: "{{ zabbix_template_group }}"

# 2. 作成したテンプレートにディスカバリルールを割り当て
- name: Create Discovery Rule under the Template
  community.zabbix.zabbix_discoveryrule:
    name: "df"
    template_name: "{{ zabbix_template_name }}"

    params:
        type: zabbix_agent
        key: 'vfs.fs.discovery'
        interval: 1h
        enabled: True

- name: Create Item Prototype  the Template
  community.zabbix.zabbix_itemprototype:
    name: '{% raw %}{#FSNAME}:Used space{% endraw %}'
    template_name: "{{ zabbix_template_name }}"
    discoveryrule_name: "df"
    params:
      type: zabbix_agent
      key: "{% raw %}vfs.fs.size[{#FSNAME},pused]{% endraw %}"
      value_type: numeric_unsigned
      interval: 5m
      status: enabled

- name: Create Trigger Prototype the Template
  community.zabbix.zabbix_triggerprototype:
    name: '{% raw %}Free disk space is less than 10% on volume {#FSNAME}{% endraw %}'
    template_name: "{{ zabbix_template_name }}"
    params:
      #severity: high
      severity: warning
      expression: '{% raw %}last(/{% endraw %}{{ zabbix_template_name }}{% raw %}/vfs.fs.size[{#FSNAME},pused])>90{% endraw %}'
      enabled: True


