---
- name: Create template
  community.zabbix.zabbix_template:
    template_name: "{{ zabbix_template_name }}"
    template_groups: "{{ zabbix_template_group }}"
    macros:
      - macro: "{$DISK_USAGE_THRESHOLD}"
        value: "90"

- name: Get Template ID
  uri:
    url: "{{ lookup('env', 'ZABBIX_URL') }}"
    method: POST
    headers:
      Content-Type: application/json-rpc
      Authorization: "Bearer {{ lookup('env', 'ZABBIX_API_TOKEN') }}"
    body_format: json
    body:
      jsonrpc: "2.0"
      method: template.get
      params:
        filter:
          host: "{{ zabbix_template_name }}"
        output: ["templateid"]
      id: 1
    return_content: yes
  register: template_id_result

# Template Items の作成
- name: Import Template Items tasks
  ansible.builtin.import_tasks: items.yml

# Discovery Rule の作成と設定
- name: Import Discovery Rule tasks
  ansible.builtin.import_tasks: discovery.yml

# Item Prototype の作成
- name: Import Item Prototype tasks
  ansible.builtin.import_tasks: itemprototype.yml

# Trigger Prototype の作成
- name: Import Trigger Prototype tasks
  ansible.builtin.import_tasks: triggerprototype.yml
