zabbix_template_name: "Linux minimal"

zabbix_template_group: Templates/Operating systems

zabbix_items:

  - name: CPU Load 1min
    key: system.cpu.load[all,avg1]
    value_type: numeric_float
    interval: 60s

  - name: Memory available %
    key: vm.memory.size[pavailable]
    value_type: numeric_float
    units: '%'
    interval: 5m

  - name: Memory usage %
    type: calculated
    key: memory.usage.percent
    value_type: numeric_float
    units: '%'
    params: '100 - last(/{HOST.HOST}/vm.memory.size[pavailable])'
    interval: 5m

  - name: Root FS usage
    key: vfs.fs.size[/,pused]
    value_type: numeric_float
    interval: 5m

  - name: Agent ping
    key: agent.ping
    value_type: numeric_unsigned
    interval: 60s

  - name: System uptime
    key: system.uptime
    value_type: numeric_unsigned
    interval: 1h

zabbix_triggers:

  - name: 'Zabbix agent is not available'
    expression: 'last(/{{ zabbix_template_name }}/agent.ping)=0'
    priority: disaster
    description: 'Zabbix agent on the host is not responding'

  - name: 'Root filesystem usage is more than {$DISK_USAGE_THRESHOLD}%'
    expression: 'last(/{{ zabbix_template_name }}/vfs.fs.size[/,pused])>{$DISK_USAGE_THRESHOLD}'
    priority: warning
    description: 'Root filesystem (/) usage has exceeded the threshold'

  - name: 'CPU load is high'
    expression: 'last(/{{ zabbix_template_name }}/system.cpu.load[all,avg1])>{$CPU_LOAD_THRESHOLD}'
    priority: average
    description: 'CPU load average (1 min) is higher than {$CPU_LOAD_THRESHOLD}'
